
STORE = [
{ question: `The Rock and Roll Hall of Fame is annually updated with the most impactful songs from prolific bands and artists in the industry.  Which set of artists have four or more songs inducted?` ,
choice1 : `Beyonce, Britany Spears, Nicki Minaj` ,
choice2 : `Mozart, Bach, Beehtoven` ,
choice3 : `James Brown, Led Zepplin, Jimi Hendrix` ,
choice4 : `Chris Rock, Jack Black, Will Smith` ,
answer : `James Brown, Led Zepplin, Jimi Hendrix` ,
icon : `https://image.freepik.com/free-icon/microphone_318-106977.jpg` ,
alt : `Music Icon` } 
, 
{ question : `Pavlov's Triangle is a psychology concept indentifying our needs, prioritizing the essentials of living, and working outward to fulfilling ourselves as people.  Which needs follow this trend?` ,
choice1 : `Safety, Belonging, Esteem` ,
choice2 : `Mind, Body, Spirit` ,
choice3 : `Sensei, Unagi, Nirvana` ,
choice4 : `Motivation, Determination, Inspiration` ,
answer : `Safety, Belonging, Esteem` ,
icon : `https://image.freepik.com/free-icon/brain-inside-human-head_318-46850.jpg` ,
alt : `Psychology Icon` } 
, 
{ question : `The word "mellifluous", according to thesaurus.com, is an adjective meaning "smooth and sweet-sounding".  Which words are considered synonymous with mellifluous?` ,
choice1 : `melancholy, mellow, mayflower` ,
choice2 : `shallow, pedantic, verbose` ,
choice3 : `sugar, love, honey` ,
choice4 : `resonant, symphonious, euphonic` ,
answer : `resonant, symphonious, euphonic` ,
icon : `https://image.freepik.com/free-icon/edit-document_318-112662.jpg` ,
alt : `Writting Icon` } 
, 
{ question : `The quiz website Sporcle.com has a popular quiz that tests users on their knowledge of African countries. Which countries are among them?` ,
choice1 : `Siam, Mongolia, Burma` ,
choice2 : `Morocco, Zambia, South Sudan` ,
choice3 : `Wakanda, Britannnia, Derkaderkastan` ,
choice4 : `Jerusal, New Kenya, Narnia` ,
answer : `Morocco, Zambia, South Sudan` ,
icon : `https://image.freepik.com/free-icon/world_318-68102.jpg` ,
alt : `World Icon` } 
, 
{ question : `The college basketball tournament March Madness is just around the corner.  Which set of mascots were part of a winning team in the tournament the past 20 years?` ,
choice1 : `Lakers, Globetrotters, Red Devils` ,
choice2 : `Lions, Tigers, Bears` ,
choice3 : `Diamondbacks, Bluejays, Steelers` ,
choice4 : `Orange, Huskies, Gators` ,
answer : `Orange, Huskies, Gators` ,
icon : `https://image.freepik.com/free-icon/ball-of-basketball_318-70995.jpg` ,
alt : `Basketball Icon` } 
, 
{ question : `I'm thinking of three words: They have 2*x letters, where (x+5)*(x-2) = 8. The words are all programming languages according to wikipedia.  What are they?` ,
choice1 : `Jewel, Pasic, Omega` ,
choice2 : `Snapchat, TinderXL, Facebook` ,
choice3 : `Matlab, Turing, Python ` ,
choice4 : `MergeSort, Functions, LogScript` ,
answer : `Matlab, Turing, Python` ,
icon : `https://image.freepik.com/free-icon/pc-computer-with-monitor_318-50338.jpg` ,
alt : `Computer Icon` } 
, 
{ question : `James Bond, also known as agent 007, is a fictional British spy played in film by an entourage of smooth, robust characters chosen for their charm and air of adventurousness.  Which set of actors have portrayed Bond on the big screen?` ,
choice1 : `Chuck Norris, Bruce Lee, Jackie Chan` ,
choice2 : `Pierce Brosnan, Sean Connery, Daniel Craig` ,
choice3 : `Jim Carrey, Adam Sandler, Mister Bean` ,
choice4 : `Tom Cruise, Wesley Snipes, Arnold Schwarzeneggar` ,
answer : `Pierce Brosnan, Sean Connery, Daniel Craig` ,
icon : `https://image.freepik.com/free-icon/movie-symbol-of-video-camera_318-70088.jpg` ,
alt : `Movie Icon` } 
, 
{ question : `Although different animal species can be grouped through common characteristics, the field of Taxonomy has categorized species' objectively by examining evolutionary similarity of their DNA, functional similarities happen to manifest from this.  Which animals are reptiles?` ,
choice1 : `Turtles, Chameleons, Crocodiles` ,
choice2 : `Amoebas, Plasmids, Prions` ,
choice3 : `Frogs, Eels, Salamanders` ,
choice4 : `Textiles, Taxes, Manifestos` ,
answer : `Turtles, Chameleons, Crocodiles` ,
icon : `https://image.freepik.com/free-icon/dove_318-107101.jpg` ,
alt : `Animal Icon` }
,
{ question : `People Magazine made a list of the top 20 biggest fads in the 2017 year based on Google results and social media trends.  Name the fads among them.` ,
choice1 : `Brothers for Beards, Chandiliering, Drone Selfies` ,
choice2 : `Neon Laces, Harry Potter Go, Pluto is a Planet` ,
choice3 : `Snapchat Hotdog, Fidget Spinners, Star Wars Porgs` ,
choice4 : `Alexa Fails, Urban Bowling, Taco Bell Challenge` ,
answer : `Snapchat Hotdog, Fidget Spinners, Star Wars Porgs` ,
icon : `https://image.freepik.com/free-icon/light-bulb_318-138116.jpg` ,
alt : `Idea Icon` } 
,
{ question : `The Seven Ancient Wonders of the World are (mostly confirmed) monumental feats by man, especially considering the resources and technology necessary for their construction in their time periods. Which set is among them?` ,
choice1 : `Mount Everest, Panama Canal, Hoover Dam` ,
choice2 : `Statue of Zeus, Colussus of Rhodes, Hanging Gardens` ,
choice3 : `Taj Mahal, Tower of Babel, Golden Gate Bridge` ,
choice4 : `Eye of Sauron, Prison of Azkaban, Bridge to Terabithia` ,
answer : `Statue of Zeus, Colussus of Rhodes, Hanging Gardens` ,
icon : `https://image.freepik.com/free-icon/bank-building_318-82143.jpg` ,
alt : `Monument Icon` } 

]